version: '3.8'

services:
  device-service:
    build: .
    ports:
      - "8083:8083"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/device_service  # внутри сети контейнеров порт 5432
      - HOST=0.0.0.0
      - PORT=8083
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    networks:
      - smarthome-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=device_service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"  # внешний порт 5433 -> внутренний 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped
    networks:
      - smarthome-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d device_service"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge